### ISSUE TITLE
Zero downtime upgrade with sparse redactional activity

### ISSUE THREAD

**Issue by shylux** [4teamwork/plone-git-deployment#13]
I have a deployment (edubs Schulseiten) which is accessed a lot but there is not that much redactional activity.
A zero downtime upgrade would be great, but i can't guarantee that there is no write collision (even though it's unlikely).

My proposal: Add a handler which retries 2 times if an upgrade runs into a db write collision. This way the zero downtime procedure can be used for smaller upgrades on non-publisher based sites.

@jone @maethu what do you think?

**Comment by jone** [comment]
@shylux if your deployment scripts are up to date you can let a single update be installed in zero-downtime mode. However, it does not handle conflicts: if there is a conflict (usually throws an `IncompleteRead` [1]), you will just need to rerun the deployment.
But be aware that each site is updated in a separate commit. When an error occurs in the second site, the first one will already be upgraded and you have an inconsistent state.

**Comment by shylux** [comment]
@jone So if one upgrade fails i could simply rerun the `update_plone` script.
I think this should work just fine - considering the deeper issues which would have to be solved to do retries.

**Comment by jone** [comment]
@shylux I forgot to describe how to make a zero-downtime deployment for a single update:
See the readme section `Deploy one commit with zero downtime` ( https://github.com/4teamwork/plone-git-deployment#zero-downtime ) for a description.
